name: verify_all

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        total: [20]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests
      run: |
        FILES=$(find . -type f -name "*.test.cpp" | sort)
        
        if [ -z "$FILES" ]; then
          exit 0
        fi

        mapfile -t FILE_ARRAY <<< "$FILES"
        TOTAL_FILES=${#FILE_ARRAY[@]}

        SHARD=${{ matrix.shard }}
        TOTAL=${{ matrix.total }}

        START=$(( SHARD * TOTAL_FILES / TOTAL ))
        END=$(( (SHARD + 1) * TOTAL_FILES / TOTAL ))
        LEN=$(( END - START ))

        TARGETS="${FILE_ARRAY[@]:START:LEN}"

        if [ -n "$TARGETS" ]; then
          oj-verify run $TARGETS
        fi